In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import re

In [7]:
dfdict={}

In [8]:
fileLen={}

In [9]:
fileList=['adani.csv',
 'AirIndia (Domestic).csv',
 'AirIndia (International).csv',
 'alphabet_stock_data.csv',
 'Alzheimer_s_Disease_and_Healthy_Aging_Data.csv',
 'Apple.csv',
 'Arrests.csv',
 'Ayurveda counts.csv',
 'Ayurveda.csv',
 'Bird Strikes.csv',
 'Budget Data.csv',
 'cancer.csv',
 'cancer_b.csv',
 'cancer_m.csv',
 'candy.csv',
 'cardekho_cleaned.csv',
 'co2-data.csv',
 'dermatology_database_1.csv',
 'ds_salaries.csv',
 'Expanded_data_with_more_features.csv',
 'fifa.csv',
 'flight_delays.csv',
 'Fortune_1000.csv',
 'Fortune_1000_Modified.csv',
 'global_power_plant_database.csv',
 'House Price India.csv',
 'ign_scores.csv',
 'imdb_movies.csv',
 'insurance.csv',
 'IPL Batting Stats.csv',
 'IPL_Batting.csv',
 'loan_data.csv',
 'MicroSoft.csv',
 'Monthly_Transportation_Statistics.csv',
 'National_Stock_Exchange_of_India_Ltd.csv',
 'papers.csv',
 'RELIANCE.csv',
 'restaurants.csv',
 'SalesDIAD.csv',
 'Sales_Analytics_2020.csv',
 'Samsung.csv',
 'smoking.csv',
 'starbucks.csv',
 'TSLA.csv',
 'twitter-stocks.csv',
 'UBER.csv',
 'Union Budget Data.csv',
 'Women_Empowerment_Data.csv',
 'World GDP.csv',
 'Zoom.csv',
 'supply_chain_data.csv',
 'test.csv',
 'train.csv',
 'Cancer_Data.csv']

In [10]:
len(fileList)

54

In [109]:
for s in fileList:
    print(s)
    dct={}
    df=pd.read_csv(s, low_memory=False)
    colList=df.columns
    #print(colList)
    for i in colList:
        if re.search(r'(?i)ID$', i) or re.search(r'(?i)zip', i) or re.search(r'(?i)month', i) or re.search(r'(?i)code', i):         #covid
            if i !='Covid':
                #print(i)
                df[i]=df[i].astype(str)
                print(df[i].dtype)
        if re.search(r'(?i)year', i) or re.search(r'(?i)date', i) or i=='published_at':
            if i!='Two Year Change' and s!='loan_data.csv' and s!='World GDP.csv':
                #print(i)
                df[i]=pd.to_datetime(df[i], format='mixed')
                print(df[i].dtype)
    file=s
    for i in df.columns:
        if i=='volume':
            print(df[i].dtype)
        #print(type(df.loc[0,i]))
        dct[i]=df[i].describe()
        #print(type(dct[i][0]))
        if dct[i].dtype==np.float64:
            dct[i]['kurtosis']=dct[i].kurtosis()
            dct[i]=dct[i].round(2)
        if df[i].dtype==np.int_ or df[i].dtype==np.float_ or df[i].dtype==np.int64:
            print(i)
            dct[i]['type']='measure'
            n=len(df[i])
            #print(df[i])
            #print(df[i].value_counts())
            if df[i].dtype==np.int_:
                if 0 in df[i].value_counts():
                    z=df[i].value_counts()[0]
                else:
                    z=0
            elif df[i].dtype==np.float_:
                df[i]=df[i].round(2)
                if 0.00 in df[i].value_counts():
                    z=(df[i].value_counts()[0.00])
                else:
                    z=0
            else:
                z=0
            dct[i]['No. Zero']=str(z)+'('+str(round((z/n)*100, 2))+'%)'
            nz=n-z
            dct[i]['No. Non Zero']=str(nz)+'('+str(round((nz/n)*100, 2))+'%)'
            hist, bins=np.histogram(df[i].dropna().values, bins=3)
            bins=bins.round(2)
            histdf={}
            print(hist)
            for k in range(len(bins)-1):
                histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'
            dct[i]['charData']=histdf
            
        else:
            if re.search(r'(?i)ID$', i) or re.search(r'(?i)zip', i) or re.search(r'(?i)month', i) or re.search(r'(?i)code', i):         #covid
                if i !='Covid':
                    if len(set(df[i]))==len(df[i]):
                        dct[i]['type']='Unique ID'
                    else:
                        dct[i]['type']='ID'
            elif re.search(r'(?i)year', i) or re.search(r'(?i)date', i) or i=='published_at':
                if i!='Two Year Change' and s!='loan_data.csv' and s!='World GDP.csv':
                    dct[i]['type']='Date'
                    dct[i]['range']=dct[i]['max']-dct[i]['min']
            else:
                dct[i]['type']='dimension'
        dct[i]=str(dct[i].to_dict())
        #print(dct[i])
    dfdict[file]=dct
    #dfdict[s]=df.select_dtypes(include='number').describe().to_dict()


adani.csv
timestamp
[ 6789 10293 14415]
open
[28859  2267   371]
high
[28868  2255   374]
low
[28786  2344   367]
close
[28842  2285   370]
int64
volume
[31444    45     8]
dividends
[31496     0     1]
stock_splits
[31494     1     2]
AirIndia (Domestic).csv
object
DEPARTURES

[ 6 22 91]
HOURS

[ 6 26 87]
KILOMETER
(TH)
[ 5 38 76]
PASSENGERS CARRIED

[ 9 40 70]
PASSENGER KMS. PERFORMED
(TH)
[ 8 34 77]
AVAILABLE SEAT KILOMETRE
(TH)
[ 5 17 97]
 PAX. LOAD FACTOR#
(IN %)
[  1   8 110]
AirIndia (International).csv
object
DEPARTURES

[24  1 94]
HOURS

[24 25 70]
KILOMETRE
(TH)
[24 29 66]
PASSENGERS CARRIED

[24 17 78]
PASSENGER KMS.PERFORMED
(TH)
[24 45 50]
AVAILABLE SEAT KILOMETRE
(TH)
[24 23 72]
alphabet_stock_data.csv
datetime64[ns]
Open
[19 72 36]
High
[19 76 32]
Low
[19 61 47]
Close
[19 78 30]
Adj Close
[19 78 30]
Volume
[101  21   5]
Alzheimer_s_Disease_and_Healthy_Aging_Data.csv
object
datetime64[ns]
datetime64[ns]
object
object
object
object
object
object
Response
[0 0 0]
Data_Value

C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'


Data_Value_Alt
[0 0 0]
Low_Confidence_Limit
[73383 31521 15846]
High_Confidence_Limit
[54384 39598 26768]
Sample_Size


C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'


[0 0 0]
StratificationCategory3
[0 0 0]
Stratification3
[0 0 0]


C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'
C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'
C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'


StratificationCategoryID3
[0 0 0]
StratificationID3
[0 0 0]
Report
[0 0 0]
Apple.csv
datetime64[ns]
Open
[9807  277  365]
High
[9801  269  379]
Low
[9805  271  373]


C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'
C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'
C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'


Close
[9804  277  368]
Adj Close
[9812  273  364]
Volume
[10432    16     1]
Arrests.csv
datetime64[ns]
Unnamed: 0
[1742 1742 1742]
age
[4149  988   89]
checks
[2705 1742  779]
Ayurveda counts.csv
datetime64[ns]
Count
[4507    5    2]
Ayurveda.csv
datetime64[ns]
Ayurveda
[68  9  3]
Ginger
[67  8  5]
Yoga
[70  5  5]
Taichi
[70  7  3]
Chinese0Medicine
[73  5  2]
Cardamom
[69  5  6]
Cumin
[71  4  5]
Brahmi
[68  9  3]
Garlic
[59 13  8]
Amla
[64  6 10]
Aswaganda
[68  9  3]
Turmeric
[68  7  5]
Acupuncture
[66 11  3]
Meditation
[68  7  5]
Mindfulness
[72  5  3]
Total
[71  6  3]
India
[68 10  2]
Germany
[68  2 10]
USA
[64 12  4]
UK
[69  8  3]
Canada
[65 11  4]
France
[78  0  2]
Australia
[71  8  1]
Europe
[71  7  2]
Nepal
[69  8  3]
Malaysia
[72  4  4]
Diabetes
[69  9  2]
Arthiritis
[64  6 10]
Alzheimers
[72  6  2]
Obesity
[69  9  2]
Cancer
[70  8  2]
Blood0Pressure
[68  5  7]
Asthma
[65 11  4]
Stress
[70  8  2]
Mental0Health
[71  8  1]
Covid
[1 2 1]
Infertility
[10  6  4]
Gotu0Kola
[66  6  8]

BRA
[261  18   7]
ESP
[230  54   2]
FRA
[177  79  30]
GER
[229  40  17]
ITA
[131 108  47]
flight_delays.csv
object
AA
[3 4 5]
AS
[6 5 1]
B6
[6 4 2]
DL
[4 4 4]
EV
[5 5 2]
F9
[3 5 4]
HA
[4 6 2]
MQ
[6 4 2]
NK
[8 3 1]
OO
[5 3 4]
UA
[3 8 1]
US
[2 2 2]
VX
[5 6 1]
WN
[3 6 3]
Fortune_1000.csv
object
rank
[333 333 334]
rank_change
[125 867   8]
revenue
[989   9   2]
profit
[989   4   4]
num. of employees
[997   0   2]
Fortune_1000_Modified.csv
rank
[333 333 334]
rank_change
[ 20 972   8]
revenue
[990   9   1]
profit
[992   4   2]
num. of employees
[998   1   1]
Market Cap
[994   3   3]
global_power_plant_database.csv
datetime64[ns]
object
datetime64[ns]
capacity_mw
[34929     6     1]
latitude
[ 1114  5349 28473]
longitude
[12229 14265  8442]
generation_gwh_2013
[6392   24    1]
generation_gwh_2014
[7123   97    6]
generation_gwh_2015
[8104   87   12]
generation_gwh_2016
[9017  105   22]
generation_gwh_2017
[9395   91   14]
generation_gwh_2018
[9561   71    5]
generation_gwh_2019
[9592   61    

Highway Vehicle Miles Traveled - Rural Other Arterial
[ 4 19 27]
Highway Vehicle Miles Traveled - Rural Interstate
[ 3 25 22]
State and Local Government Construction Spending - Breakwater/Jetty
[210 131  21]
State and Local Government Construction Spending - Dam/Levee
[179 130  53]
State and Local Government Construction Spending - Conservation and Development
[185 131  46]
State and Local Government Construction Spending - Pump Station
[232 116  14]
State and Local Government Construction Spending - Line
[203 146  13]
State and Local Government Construction Spending - Water Treatment Plant
[105 205  52]
State and Local Government Construction Spending - Water Supply
[143 203  16]
State and Local Government Construction Spending - Line/Drain
[306  41  15]
State and Local Government Construction Spending - Waste Water Treatment Plant
[168 161  33]
State and Local Government Construction Spending - Waste Water
[210 129  23]
State and Local Government Construction Spending - Line/Pump Sta

object
datetime64[ns]
citation_count
[121793      9      1]
RELIANCE.csv
datetime64[ns]
Prev Close
[3899  965  211]
Open
[3954  934  187]
High
[3938  928  209]
Low
[3885  973  217]
Last
[3894  972  209]
Close
[3898  966  211]
VWAP
[3896  962  217]
Volume
[5026   43    6]
Turnover
[5044   26    5]
Trades
[2175   44    6]
Deliverable Volume
[4541   18    2]
%Deliverble
[1490 2920  151]
restaurants.csv
Rating
[ 199  760 5634]
Votes
[6560   30    3]
Cost
[6381  210    2]
SalesDIAD.csv
object
datetime64[ns]
object
object
object
Units
[      0 1048575       0]
Revenue
[875101 165467   8007]
MSRP
[811087 210186  27302]
ManufacturerID.1
[434600 376102 237873]
Sales_Analytics_2020.csv
object
object
datetime64[ns]
datetime64[ns]
object
object
object
Sales
[9981   11    2]
Quantity
[8131 1693  170]
Discount
[8601  537  856]
Profit
[  11 9977    6]
Samsung.csv
datetime64[ns]
Open
[4234 1004  383]
High
[4278  972  371]
Low
[4235 1001  385]
Close
[4242 1002  377]
Adj Close
[4301  946  374]
Volume
[5

C:\Users\DELL\AppData\Local\Temp\ipykernel_8708\2621834778.py:55: RuntimeWarning: invalid value encountered in scalar divide
  histdf[str(bins[k])+' - '+str(bins[k+1])]=str(hist[k])+'('+str(round((hist[k]/sum(hist))*100, 2))+'%)'


In [110]:
dfdict

{'adani.csv': {'timestamp': "{'count': 31497.0, 'mean': 1.409762306791123e+18, 'std': 1.8179378692740022e+17, 'min': 1.0254618e+18, '25%': 1.2670362e+18, '50%': 1.4349114e+18, '75%': 1.5698681999999997e+18, 'max': 1.6770905999999997e+18, 'kurtosis': -0.39, 'type': 'measure', 'No. Zero': '0(0.0%)', 'No. Non Zero': '31497(100.0%)', 'charData': {'1.0254618e+18 - 1.2426714e+18': '6789(21.55%)', '1.2426714e+18 - 1.459881e+18': '10293(32.68%)', '1.459881e+18 - 1.6770905999999997e+18': '14415(45.77%)'}}",
  'symbol': "{'count': 31497, 'unique': 10, 'top': 'ADANIENT', 'freq': 5135, 'type': 'dimension'}",
  'company': "{'count': 31497, 'unique': 10, 'top': 'Adani Enterprises Limited', 'freq': 5135, 'type': 'dimension'}",
  'open': "{'count': 31497.0, 'mean': 404.54, 'std': 623.11, 'min': -0.01, '25%': 59.42, '50%': 140.1, '75%': 384.28, 'max': 4175.0, 'kurtosis': 7.61, 'type': 'measure', 'No. Zero': '0(0.0%)', 'No. Non Zero': '31497(100.0%)', 'charData': {'-0.01 - 1391.66': '28859(91.62%)', '13

In [13]:
for i in dfdict:
    v=dfdict
    print(i, v)

TypeError: cannot unpack non-iterable builtin_function_or_method object

In [111]:
maindf=pd.DataFrame(dfdict)

In [112]:
maindf

adani.csv   
timestamp                {'count': 31497.0, 'mean': 1.409762306791123e+...  \
symbol                   {'count': 31497, 'unique': 10, 'top': 'ADANIEN...   
company                  {'count': 31497, 'unique': 10, 'top': 'Adani E...   
open                     {'count': 31497.0, 'mean': 404.54, 'std': 623....   
high                     {'count': 31497.0, 'mean': 411.75, 'std': 633....   
...                                                                    ...   
concavity_worst                                                        NaN   
concave points_worst                                                   NaN   
symmetry_worst                                                         NaN   
fractal_dimension_worst                                                NaN   
Unnamed: 32                                                            NaN   

                        AirIndia (Domestic).csv AirIndia (International).csv   
timestamp                                   NaN                          NaN  \
symbol                                      NaN                          NaN   
company                                     NaN                          NaN   
open                                        NaN                          NaN   
high                                        NaN                          NaN   
...                                         ...                          ...   
concavity_worst                             NaN                          NaN   
concave points_worst                        NaN                          NaN   
symmetry_worst                              NaN                          NaN   
fractal_dimension_worst                     NaN                          NaN   
Unnamed: 32                                 NaN                          NaN   

                        alphabet_stock_data.csv   
timestamp                                   NaN  \
symbol                                      NaN   
company                                     NaN   
open                                        NaN   
high                                        NaN   
...                                         ...   
concavity_worst                             NaN   
concave points_worst                        NaN   
symmetry_worst                              NaN   
fractal_dimension_worst                     NaN   
Unnamed: 32                                 NaN   

                        Alzheimer_s_Disease_and_Healthy_Aging_Data.csv   
timestamp                                                          NaN  \
symbol                                                             NaN   
company                                                            NaN   
open                                                               NaN   
high                                                               NaN   
...                                                                ...   
concavity_worst                                                    NaN   
concave points_worst                                               NaN   
symmetry_worst                                                     NaN   
fractal_dimension_worst                                            NaN   
Unnamed: 32                                                        NaN   

                        Apple.csv Arrests.csv Ayurveda counts.csv   
timestamp                     NaN         NaN                 NaN  \
symbol                        NaN         NaN                 NaN   
company                       NaN         NaN                 NaN   
open                          NaN         NaN                 NaN   
high                          NaN         NaN                 NaN   
...                           ...         ...                 ...   
concavity_worst               NaN         NaN                 NaN   
concave points_worst          NaN         NaN                 NaN   
symmetry_worst                NaN         Na

In [113]:
maindf=maindf.transpose()

In [114]:
maindf=maindf.stack()

In [115]:
for i in fileList:
    print(i)
    print(maindf[i])

adani.csv
timestamp       {'count': 31497.0, 'mean': 1.409762306791123e+...
symbol          {'count': 31497, 'unique': 10, 'top': 'ADANIEN...
company         {'count': 31497, 'unique': 10, 'top': 'Adani E...
open            {'count': 31497.0, 'mean': 404.54, 'std': 623....
high            {'count': 31497.0, 'mean': 411.75, 'std': 633....
low             {'count': 31497.0, 'mean': 396.69, 'std': 610....
close           {'count': 31497.0, 'mean': 404.17, 'std': 622....
volume          {'count': 31497.0, 'mean': 3594056.38, 'std': ...
dividends       {'count': 31497.0, 'mean': 0.02, 'std': 0.53, ...
stock_splits    {'count': 31497.0, 'mean': 0.0, 'std': 0.04, '...
dtype: object
AirIndia (Domestic).csv
Month                             {'count': 119, 'unique': 12, 'top': 'APR', 'fr...
DEPARTURES\n                      {'count': 119.0, 'mean': 8247.68, 'std': 2036....
HOURS\n                           {'count': 119.0, 'mean': 15211.57, 'std': 3772...
KILOMETER\n(TH)                   {'coun

In [116]:
maindf

adani.csv        timestamp                  {'count': 31497.0, 'mean': 1.409762306791123e+...
                 symbol                     {'count': 31497, 'unique': 10, 'top': 'ADANIEN...
                 company                    {'count': 31497, 'unique': 10, 'top': 'Adani E...
                 open                       {'count': 31497.0, 'mean': 404.54, 'std': 623....
                 high                       {'count': 31497.0, 'mean': 411.75, 'std': 633....
                                                                  ...                        
Cancer_Data.csv  concavity_worst            {'count': 569.0, 'mean': 0.27, 'std': 0.21, 'm...
                 concave points_worst       {'count': 569.0, 'mean': 0.11, 'std': 0.07, 'm...
                 symmetry_worst             {'count': 569.0, 'mean': 0.29, 'std': 0.06, 'm...
                 fractal_dimension_worst    {'count': 569.0, 'mean': 0.08, 'std': 0.02, 'm...
                 Unnamed: 32                {'count': 0.0, '

In [117]:
maindf[('Apple.csv', 'Open')]

"{'count': 10449.0, 'mean': 14.53, 'std': 31.48, 'min': 0.05, '25%': 0.28, '50%': 0.47, '75%': 14.53, 'max': 182.63, 'kurtosis': 7.99, 'type': 'measure', 'No. Zero': '0(0.0%)', 'No. Non Zero': '10449(100.0%)', 'charData': {'0.05 - 60.91': '9807(93.86%)', '60.91 - 121.77': '277(2.65%)', '121.77 - 182.63': '365(3.49%)'}}"

In [118]:
maindf=maindf.to_frame()

In [119]:
maindf=maindf.reset_index()

In [120]:
maindf.rename(columns={'level_0':'file', 'level_1':'column', 0:'desc'}, inplace=True)

In [121]:
maindf.columns

Index(['file', 'column', 'desc'], dtype='object')

In [122]:
maindf.loc[0, 'desc']

"{'count': 31497.0, 'mean': 1.409762306791123e+18, 'std': 1.8179378692740022e+17, 'min': 1.0254618e+18, '25%': 1.2670362e+18, '50%': 1.4349114e+18, '75%': 1.5698681999999997e+18, 'max': 1.6770905999999997e+18, 'kurtosis': -0.39, 'type': 'measure', 'No. Zero': '0(0.0%)', 'No. Non Zero': '31497(100.0%)', 'charData': {'1.0254618e+18 - 1.2426714e+18': '6789(21.55%)', '1.2426714e+18 - 1.459881e+18': '10293(32.68%)', '1.459881e+18 - 1.6770905999999997e+18': '14415(45.77%)'}}"

In [58]:
maindf.groupby('file').size()

file
AirIndia (Domestic).csv                             9
AirIndia (International).csv                        9
Alzheimer_s_Disease_and_Healthy_Aging_Data.csv     39
Apple.csv                                           7
Arrests.csv                                         9
Ayurveda counts.csv                                 4
Ayurveda.csv                                       55
Bird Strikes.csv                                   23
Budget Data.csv                                    13
Cancer_Data.csv                                    33
Expanded_data_with_more_features.csv               15
Fortune_1000.csv                                   20
Fortune_1000_Modified.csv                          18
House Price India.csv                              23
IPL Batting Stats.csv                              17
IPL_Batting.csv                                    17
MicroSoft.csv                                       7
Monthly_Transportation_Statistics.csv             136
National_Stock_Exchange

In [59]:
fileLen

{}

In [10]:
checkdf=pd.read_csv('adani.csv')

In [35]:
type(checkdf.describe())

pandas.core.frame.DataFrame

In [47]:
round(checkdf.describe().loc['max','timestamp'])

1677090600000000000

In [125]:
maindf.to_csv('description.csv', index=False)

In [109]:
ind=pd.date_range(start='1/1/2022', end='31/1/2022')

In [110]:
datedf=pd.DataFrame(ind)

In [112]:
datedf.describe()

0
count                   31
mean   2022-01-16 00:00:00
min    2022-01-01 00:00:00
25%    2022-01-08 12:00:00
50%    2022-01-16 00:00:00
75%    2022-01-23 12:00:00
max    2022-01-31 00:00:00

In [121]:
df=pd.read_csv('Sales_Analytics_2020.csv', parse_dates=['Ship Date'])

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Row ID         9994 non-null   int64         
 1   Order ID       9994 non-null   object        
 2   Order Date     9994 non-null   object        
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object        
 5   Customer ID    9994 non-null   object        
 6   Customer Name  9994 non-null   object        
 7   Segment        9994 non-null   object        
 8   Country        9994 non-null   object        
 9   City           9994 non-null   object        
 10  State          9994 non-null   object        
 11  Postal Code    9994 non-null   int64         
 12  Region         9994 non-null   object        
 13  Product ID     9994 non-null   object        
 14  Category       9994 non-null   object        
 15  Sub-Category   9994 n